### PR TITLE
add stability tester

### PR DESCRIPTION
**Pull request by nolouch**
PTAL @iamxy @silentsai @siddontang

### CODE REVIEW

**Comment by siddontang** [comment]
Can we not contain tidb in vendor, it is too huge.

**Comment by nolouch** [comment]
we use tidb as a package in the test, maybe we can use tidb vendor directly when compiling the stability tester, and remove vendor in here?

**Comment by siddontang** [comment]
I prefer removing vendor here, it is too huge.

**Comment by nolouch** [comment]
PTAL @siddontang @silentsai

**Comment by siddontang** [comment]
LGTM

**Comment by iamxy** [comment]
I suggest download tidb binary directly, not need to checkout and compile from source code.

e.g.
```
curl "http://pingcap-dev.hk.ufileos.com/builds/pingcap/tidb/${TIDB_SHA1}/centos7/tidb-server.tar.gz | tar xz
```

or you also can send request to `build-bot` server to build a binary immediately.

**Review by iamxy — APPROVED** [review]

**Comment by iamxy** [comment]
LGTM

**Pull request merged**
