### PR TITLE
bank: add a remark column for avoiding only store as short value

### PR DESCRIPTION
**Pull request by nolouch**
@disksing @zhangjinpeng1987 PTAL

### CODE REVIEW

**Review by zhangjinpeng87 — COMMENTED** [review]
LGTM

**Comment by cwen0** [comment]
why add this column?

**Comment by nolouch** [comment]
In prewrite phase, if `value` short than 64 bytes, it will store into lock cf as a short value.

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
