### PR TITLE
Support TLS connection in raw:// and tikv:// protocol for ycsb

### PR DESCRIPTION
**Pull request by breezewish**
based on https://github.com/pingcap/octopus/pull/69

Usage:

```bash
ycsb -ssl-ca xxxx/cfssl/ca.pem --ssl-cert xxxx/cfssl/client.pem --ssl-key xxxx/cfssl/client-key.pem ........
```

### CODE REVIEW

**Comment by breezewish** [comment]
@AndreMouche PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by AndreMouche** [comment]
It's a little hard for me to understand, invite any other reviewers?

**Comment by breezewish** [comment]
Ok.. @zz-jason PTAL

**Comment by zz-jason** [comment]
I'm going to close this PR since it hasn't been updated for a long time. Feel free to reopen it once you wish to advance this PR in the future.

**Pull request closed without merging**
